### ISSUE TITLE
Hide menu when no flex-bison project is open.

### ISSUE THREAD

**Issue by V4570** [dimtsiakm/ide-flex-bison#1]
Great work with the plugin!!
It would be much appreciated if there was an option to hide the IDE menu when working on something other than a flex-bison project. This could either be added as a default configuration or an option in the settings.

**Comment by dimtsiakm** [comment]
Thank you for your report. 

Now you can hide the toolbar from menu Packages > Flex Bison IDE > Toggle Toolbar or right click into texteditor > Toggle Flex-Bison Toolbar
